Django/hellodjango/hellodjango/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage.views import HomepageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'))
]

Django/hellodjango/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.HomepageView.as_view(), name='index'),
    path('view/', views.IndexView.as_view(), name='view'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

Django/hellodjango/homepage/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

Django/hellodjango/homepage/views.py
from django.views.generic import TemplateView, ListView, DetailView
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Question

class HomepageView(TemplateView):
    template_name = 'index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['statement'] = 'I love Snickers the cat'
        return context

    def say_bye(self):
        return 'Goodbye'
    
class IndexView(ListView):
    template_name = 'view.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')

class DetailView(DetailView):
    model = Question
    template_name = 'detail.html'

class ResultsView(DetailView):
    model = Question
    template_name = 'results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'detail.html', {'question': question, 'error_message': "You didn't select a choice"})
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('homepage:results', args=(question_id,)))

Django/hellodjango/homepage/templates/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <p><strong>
    {{ error_message }}
    </strong></p>
{% endif %}

<form action="{% url 'homepage:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for-"choice{{ forloop.counter }}">{{choice.choice_text}}</label>
    <br>
{% endfor %}
    <input type="submit" value="Vote">
</form>

Django/hellodjango/homepage/templates/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'homepage:detail' question.id %}">Vote again?</a>

Django/hellodjango/homepage/templates/view.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'homepage:detail' question.id%}">{{ question.question_text }}</a></li>
    {% endfor %} 
    </ul>
{% else %}
    <p>No polls are available </p>
{% endif %}

Django/hellodjango/templates/index.html
<h1>Home Page</h1>
<p>{{ statement }}</p>
{{view.say_bye}}